export const stages = [
  {
    id: '1',
    name: 'Toma de contacto',
    icon: '🌟',
    gameMode: 'test',
    numQuestions: 10,
    requiredCorrect: 5,
    timeConstraint: null,
    consecutiveWins: 1,
    description: '5 de 10 · Tipo test · Sin tiempo',
  },
  {
    id: '2',
    name: 'Contrarreloj',
    icon: '⏱️',
    gameMode: 'test',
    numQuestions: 10,
    requiredCorrect: 8,
    timeConstraint: { type: 'total', seconds: 60 },
    consecutiveWins: 1,
    description: '8 de 10 · Tipo test · < 1 min',
  },
  {
    id: '3',
    name: 'Teclado exprés',
    icon: '⌨️',
    gameMode: 'input',
    numQuestions: 10,
    requiredCorrect: 8,
    timeConstraint: { type: 'total', seconds: 120 },
    consecutiveWins: 1,
    description: '8 de 10 · Teclado · < 2 min',
  },
  {
    id: '4',
    name: 'Presión',
    icon: '🔥',
    gameMode: 'test',
    numQuestions: 10,
    requiredCorrect: 9,
    timeConstraint: { type: 'perQuestion', seconds: 5 },
    consecutiveWins: 1,
    description: '9 de 10 · Tipo test · 5s',
  },
  {
    id: '5',
    name: 'Agilidad mental',
    icon: '🧠',
    gameMode: 'input',
    numQuestions: 10,
    requiredCorrect: 9,
    timeConstraint: { type: 'perQuestion', seconds: 10 },
    consecutiveWins: 1,
    description: '9 de 10 · Teclado · 10s',
  },
  {
    id: '6',
    name: 'Alta velocidad',
    icon: '⚡',
    gameMode: 'input',
    numQuestions: 10,
    requiredCorrect: 9,
    timeConstraint: { type: 'perQuestion', seconds: 5 },
    consecutiveWins: 1,
    description: '9 de 10 · Teclado · 5s',
  },
  {
    id: '7',
    name: 'Maratón',
    icon: '🏃',
    gameMode: 'input',
    numQuestions: 20,
    requiredCorrect: 18,
    timeConstraint: { type: 'perQuestion', seconds: 5 },
    consecutiveWins: 1,
    description: '18 de 20 · Teclado · 5s',
  },
  {
    id: '8',
    name: 'Final Boss',
    icon: '👑',
    gameMode: 'input',
    numQuestions: 20,
    requiredCorrect: 20,
    timeConstraint: { type: 'perQuestion', seconds: 5 },
    consecutiveWins: 2,
    description: '20/20 · 2 veces seguidas · 5s',
  },
]

export function getStageById(id) {
  return stages.find(s => s.id === id)
}
